version: '3.8'

services:
  mysql_dev:
    image: mysql:8.0
    container_name: mysql_dev
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: ecommerce_db
    ports:
      - "3307:3306"
    volumes:
      - ~/mysql_data:/var/lib/mysql
    networks:
      - dev_network

  phpmyadmin_dev:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_dev
    environment:
      PMA_HOST: mysql_dev
      PMA_USER: root
      PMA_PASSWORD: root123
    ports:
      - "8081:80"
    depends_on:
      - mysql_dev
    networks:
      - dev_network

  xampp_dev:
    image: tomsik68/xampp
    container_name: xampp_dev
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/joao-victor/my_web_pages:/www
    networks:
      - dev_network

  spring_app:
    build: .
    container_name: spring_app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_dev:3306/ecommerce_db?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root123
    depends_on:
      - mysql_dev
    networks:
      - dev_network

networks:
  dev_network:
    driver: bridge
